services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  async_api:
    build: .
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 8001:8001
    env_file:
      - src/core/.env

  redis:
    image: redis:latest
    ports:
      - 6379:6379